MountainAir.Web/Models/PackageViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using MountainAir.Common.Data.Models;

namespace MountainAir.Web.Models;

public class AddPackageItemViewModel
{
    public Package Package { get; set; }

    public SelectList Categories { get; set; }

    public PackageItem PackageItem { get; internal set; }
}

public class AddPackageMaterialViewModel
{
    public Package Package { get; set; }

    public SelectList Categories { get; set; }

    public PackageItem PackageItem { get; internal set; }

    public CatalogItem CatalogItem { get; internal set; }
}

public class CategorySelectionModel 
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string Group { get; set; }
}

MountainAir.Web/Models/Packages/PackageMaterialViewModel.cs
namespace MountainAir.Web.Models.Packages;

public class PackageMaterialViewModel
{
    public int? Labor { get; set; }

    public decimal? Price { get; set; }

    public int Quantity { get; set; }

    public string Description { get; set; }

    public string CatalogNumber { get; set; }

    public string ModelNumber { get; set; }

    public int PackageMaterialId { get; set; }

    public bool Active { get; set; }
}

MountainAir.Web/Controllers/PackagesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MountainAir.Common.Data;
using MountainAir.Common.Data.Models;
using MountainAir.Common.Security;
using MountainAir.Web.Models;
using MountainAir.Web.Models.Packages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Diagnostics;
using MountainAir.Web.Models.DataTables;
using NLog.Targets;

namespace MountainAir.Web.Controllers;

[RoleAuthorize(Roles.Administrators, Roles.CanEditCatalog)]
public class PackagesController : BaseController
{
    public PackagesController(ApplicationDbContext applicationDbContext) : base(applicationDbContext)
    {
    }

    public IActionResult Index()
    {
        var data = AppContext.Packages.OrderBy(i => i.PackageName).ToList();

        return View(data);
    }

    public async Task<IActionResult> PackageItems(int id)
    {
        var package = await AppContext.Packages.FirstOrDefaultAsync(i => i.PackageId == id);

        var categories = await AppContext.Categories
            .Where(c => !c.MaterialCategory)
            .Include(p => p.CatalogItems.Where(c => !string.IsNullOrWhiteSpace(c.ModelNum)))
            .ToListAsync();

        var catalogItems = categories.SelectMany(ca => ca.CatalogItems.Select(ni => new EditorSelectOption()
        {
            Label = $"{ca.CategoryName} - {ni.ModelNum}",
            Value = ni.CatalogItemId
        })).OrderBy(c => c.Label).ToList();

        return View(new PackageEditingModel()
        {
            Package = package,
            CatalogItems = catalogItems
        });
    }

    #region Package API Endpoints

    [HttpGet, Route("api/[Controller]/[Action]")]
    public async Task<JsonResult> GetPackages()
    {
        try
        {
            var data = await AppContext.Packages.OrderBy(i => i.PackageName).ToListAsync();

            return Json(new JsonResponseModel(data));
        }
        catch (Exception ex)
        {
            return Json(new JsonResponseModel()
            {
                Error = ex.GetBaseException().Message
            });
        }
    }
        
    [HttpPost, Route("api/[Controller]/[Action]")]
    public async Task<JsonResult> UpdatePackageData(UpdateModel model)
    {
        try
        {
            var data = new List<Package>();

            switch (model.Action)
            {
                case UpdateActions.Remove:
                    await RemovePackageAsync(model.Data);
                    break;
                case UpdateActions.Edit:
                    data.AddRange(await UpdatePackage(model.Data));
                    break;
                case UpdateActions.Create:
                    data.AddRange(await CreatePackage(model.Data));
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }

            return Json(new EditorResponse<Package>(data));
        }
        catch (Exception ex)
        {
            return Json(new EditorResponse<Package>()
            {
                Error = ex.GetBaseException().Message
            });
        }
    }

    private async Task<IEnumerable<Package>> CreatePackage(DataBag data)
    {
        var retval = new List<Package>();

        foreach (var key in data.Keys)
        {
            var model = data[key];

            var newPackage = new Package();

            data.FillObject(key, newPackage);

            newPackage.AddDate = DateTime.Now;
            newPackage.AddBy = CurrentUser.Id;
            newPackage.Active = true;

            AppContext.Packages.Add(newPackage);

            retval.Add(newPackage);
        }

        await AppContext.SaveChangesAsync();

        return retval;
    }

    private async Task<IEnumerable<Package>> UpdatePackage(DataBag data)
    {
        var retval = new List<Package>();

        foreach (var key in data.Keys)
        {
            if(!int.TryParse(key, out int rowId))
                continue;

            var package = await AppContext.Packages.FirstOrDefaultAsync(p => p.PackageId == rowId);

            if (package == null)
                continue;
                
            var model = data[key];

            if (model.TryGetValue("packageName", out string packageName) && !string.IsNullOrWhiteSpace(packageName))
            {
                package.PackageName = packageName;
            }
                
            if (model.TryGetValue("ahriRating", out string ahriRating))
            {
                package.AhriRating = ahriRating;
            }
                
            if (model.TryGetValue("profitMargin", out string profitMargin) && decimal.TryParse(profitMargin, out decimal pm))
            {
                package.ProfitMargin = pm;
            }
                
            if (model.TryGetValue("active", out string active) && bool.TryParse(active, out bool act))
            {
                package.Active = act;
            }

            AppContext.Packages.Update(package);

            retval.Add(package);
        }

        await AppContext.SaveChangesAsync();

        return retval;
    }

    private async Task RemovePackageAsync(DataBag data)
    {
        var rowIds = new List<int>();

        foreach (var key in data.Keys)
        {
            if(!int.TryParse(key, out int rowId))
                continue;
            rowIds.Add(rowId);
        }

        var packages = await AppContext.Packages
            .Where(p => rowIds.Contains(p.PackageId))
            .Include(p => p.PackageItems)
            .ThenInclude(p => p.PackageMaterials)
            .ToListAsync();

        if (!packages.Any())
        {
            return;
        }

        await using var trans = await AppContext.Database.BeginTransactionAsync();

        try
        {
            var materials = packages.SelectMany(p => p.PackageItems.SelectMany(pi => pi.PackageMaterials)).ToList();

            if (materials.Any())
            {
                AppContext.PackageMaterials.RemoveRange(materials);
            }

            var packageItems = packages.SelectMany(p => p.PackageItems).ToList();

            if (packageItems.Any())
            {
                AppContext.PackageItems.RemoveRange(packageItems);
            }

            AppContext.Packages.RemoveRange(packages);
                
            await AppContext.SaveChangesAsync();

            await trans.CommitAsync();
        }
        catch
        {
            await trans.RollbackAsync();
            throw;
        }
    }

    #endregion

    #region API Endpoints

    [HttpGet, Route("api/[Controller]/[Action]/{categoryId}")]
    public async Task<JsonResult> GetCatalogItems(int categoryId)
    {
        var items = await AppContext.CatalogItems
            .Where(i => i.CategoryId == categoryId && i.Active == true)
            .OrderBy(i => i.CatalogNum)
            .ThenBy(i => i.Descr)
            .ToListAsync();

        return Json(new JsonResponseModel<CatalogItem>(items));
    }

    [HttpGet, Route("api/[Controller]/[Action]/{id}")]
    public async Task<JsonResult> GetPackageItems(int id)
    {
        try
        {
            var items = await AppContext.PackageItems
                .Where(i => i.PackageId == id)
                .Include(i => i.CatalogItem)
                .ToListAsync();

            return Json(new JsonResponseModel(items));
        }
        catch (Exception ex)
        {
            return Json(new JsonResponseModel()
            {
                Error = ex.GetBaseException().Message
            });
        }
    }
        
    [HttpGet, Route("api/[Controller]/[Action]/{id}")]
    public async Task<JsonResult> GetPackageMaterialItems(int id)
    {
        try
        {
            var items = await AppContext.PackageMaterials
                .Where(i => i.PackageMaterialId == id)
                .Include(i => i.CatalogItem)
                .ToListAsync();

            return Json(new JsonResponseModel(items));
        }
        catch (Exception ex)
        {
            return Json(new JsonResponseModel()
            {
                Error = ex.GetBaseException().Message
            });
        }
    }

    #endregion

    #region Packages

    [HttpGet]
    public IActionResult AddPackage()
    {
        return View(new Package());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult AddPackage(Package model)
    {
        if(!ModelState.IsValid)
        {
            return View(model);
        }

        try
        {
            model.AddBy = CurrentUser.Id;
            model.AddDate = DateTime.Now;
            AppContext.Packages.Add(model);
            AppContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        catch(Exception ex)
        {
            AddStatusMessage(ex);
        }

        return View(model);
    }

    [HttpGet, Route("[Controller]/[Action]/{packageId}")]
    public async Task<IActionResult> EditPackage(int packageId)
    {
        var data = await AppContext.Packages
            .Include(i => i.PackageItems)
            .ThenInclude(i => i.CatalogItem)
            .FirstOrDefaultAsync(i => i.PackageId == packageId);

        if (data == null)
            return NotFound();

        //data.PackageItems.ForEach(item =>
        //{
        //    AppContext.Entry(item).Reference(nameof(PackageItem.CatalogItem)).Load();
        //});

        return View(data);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult EditPackage(int id, Package model)
    {
        if(!ModelState.IsValid)
        {
            return View(model);
        }

        var exists = AppContext.Packages.Any(i => i.PackageId == id);

        if(!exists)
        {
            return BadRequest();
        }

        try
        {
            model.UpdatedBy = CurrentUser.Id;
            model.UpdatedDate = DateTime.Now;

MountainAir.Web/Views/Packages/AddPackage.cshtml
@model MountainAir.Common.Data.Models.Package

@{
    ViewData["Title"] = "Add Package";
    NavPages.AddActivePage(ViewData, NavPages.Pages.Packages);
}

<div class="card">
    <div class="card-header">
        <div>
            <h5 class="card-title">@ViewData["Title"]</h5>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="AddPackage">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="mb-3">
                        <label asp-for="PackageName" class="control-label"></label>
                        <input asp-for="PackageName" class="form-control" />
                        <span asp-validation-for="PackageName" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <div class="checkbox">
                            <label>
                                <input asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                            </label>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label asp-for="ProfitMargin" class="control-label"></label>
                        <input asp-for="ProfitMargin" class="form-control" />
                        <span asp-validation-for="ProfitMargin" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

MountainAir.Web/Views/Packages/AddPackageItem.cshtml
@model MountainAir.Web.Models.AddPackageItemViewModel
@{
    ViewData["Title"] = "Add Equipment";
    NavPages.AddActivePage(ViewData, NavPages.Pages.Packages);
}

<div class="card">
    <div class="card-header d-flex justify-content-between">
        <h5 class="card-title">@ViewData["Title"]</h5>
        <a asp-action="EditPackage" asp-controller="Packages" asp-route-id="@Model.Package.PackageId" class="btn btn-sm btn-secondary">Back To Package</a>
    </div>
    <div class="card-body">
        <div class="row">
            <input type="hidden" id="hidPackageId" asp-for="Package.PackageId" />
            <div class="col">
                <div class="mb-3">
                    <label asp-for="Package.PackageName" class="form-label"></label>
                    <input asp-for="Package.PackageName" class="form-control" readonly />
                </div>
            </div>
            <div class="col">
                <div class="mb-3">
                    <label class="form-label">Categories</label>
                    <select id="ddlCategories" class="form-control custom-select" asp-items="Model.Categories">
                        <option value="0">Select</option>
                    </select>
                </div>
            </div>
        </div>
        <hr />
        <table id="tblCatalogItems" class="table table-condensed table-striped" style="font-size:0.8em;">
            <thead></thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
<script src="~/js/Packages/AddPackageItem.js"></script>
}

MountainAir.Web/Views/Packages/AddPackageMaterial.cshtml
@model MountainAir.Web.Models.AddPackageMaterialViewModel
@{
    ViewData["Title"] = "Add Material";
    NavPages.AddActivePage(ViewData, NavPages.Pages.Packages);
}

<div class="card">
    <div class="card-header d-flex justify-content-between">
        <h5 class="card-title">@ViewData["Title"]</h5>
        <a asp-action="EditPackageItem" asp-controller="Packages" asp-route-id="@Model.PackageItem.PackageItemId" class="btn btn-sm btn-secondary">Back to Equipment</a>
    </div>
    <div class="card-body">
        <div class="row">
            <input type="hidden" id="hidPackageItemId" asp-for="PackageItem.PackageItemId" />
            <div class="col">
                <div class="mb-3">
                    <label asp-for="CatalogItem.ModelNum" class="form-label"></label>
                    <input asp-for="CatalogItem.ModelNum" class="form-control" readonly />
                </div>
            </div>
            <div class="col">
                <div class="mb-3">
                    <label asp-for="CatalogItem.CatalogNum" class="form-label"></label>
                    <input asp-for="CatalogItem.CatalogNum" class="form-control" readonly />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="mb-3">
                    <label asp-for="CatalogItem.Descr" class="form-label"></label>
                    <input asp-for="CatalogItem.Descr" class="form-control" readonly />
                </div>
            </div>
            <div class="col">
                <div class="mb-3">
                    <label asp-for="CatalogItem.CustomerDesc" class="form-label"></label>
                    <input asp-for="CatalogItem.CustomerDesc" class="form-control" readonly />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="mb-3">
                    <label class="form-label">Categories</label>
                    <select id="ddlCategories" class="form-control custom-select" asp-items="Model.Categories">
                        <option value="0">Select</option>
                    </select>
                </div>
            </div>
            <div class="col">
            </div>
        </div>
        <hr />
        <table id="tblCatalogItems" class="table table-condensed table-striped">
            <thead></thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
<script src="~/js/Packages/AddPackageMaterial.js"></script>
}

MountainAir.Web/Views/Packages/DeletePackage.cshtml
@model MountainAir.Common.Data.Models.Package
@{
    ViewData["Title"] = "Delete Package";
    NavPages.AddActivePage(ViewData, NavPages.Pages.Packages);
}

<h3 class="alert alert-danger" role="alert">Are you sure you want to delete this?</h3>

<div class="card">
    <div class="card-header">
        <div>
            <h5 class="card-title">@ViewData["Title"]</h5>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="DeletePackage">
                    <input asp-for="PackageId" type="hidden" />
                    <div class="mb-3">
                        <label asp-for="PackageName" class="control-label"></label>
                        <input asp-for="PackageName" class="form-control" readonly />
                    </div>
                    <div class="mb-3">
                        <label asp-for="ProfitMargin" class="control-label"></label>
                        <input asp-for="ProfitMargin" class="form-control" readonly />
                    </div>
                    <div class="mb-3">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MountainAir.Web/Views/Packages/DeletePackageItem.cshtml
@model MountainAir.Common.Data.Models.PackageItem
@{
    ViewData["Title"] = "Delete Equipment";
    NavPages.AddActivePage(ViewData, NavPages.Pages.Packages);
}
<h3 class="alert alert-danger" role="alert">Are you sure you want to delete this?</h3>
<div class="card">
    <div class="card-header">
        <div>
            <h5 class="card-title">@ViewData["Title"]</h5>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="DeletePackageItem">
                    <input asp-for="PackageItemId" type="hidden" />
                    <div class="mb-3">
                        <label asp-for="CatalogItem.ModelNum" class="form-label"></label>
                        <input asp-for="CatalogItem.ModelNum" class="form-control" readonly />
                    </div>
                    <div class="mb-3">
                        <label asp-for="CatalogItem.Descr" class="form-label"></label>
                        <input asp-for="CatalogItem.Descr" class="form-control" readonly />
                    </div>
                    <div class="mb-3">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        <a class="btn btn-secondary" asp-action="EditPackage" asp-route-id="@Model.PackageId">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MountainAir.Web/Views/Packages/DeletePackageMaterial.cshtml
@model MountainAir.Common.Data.Models.PackageMaterial
@{
    ViewData["Title"] = "Delete Material";
    NavPages.AddActivePage(ViewData, NavPages.Pages.Packages);
}
<h3 class="alert alert-danger" role="alert">Are you sure you want to delete this?</h3>
<div class="card">
    <div class="card-header">
        <div>
            <h5 class="card-title">@ViewData["Title"]</h5>
        </div>
    </div>
    <div class="card-body">
        <form asp-action="DeletePackageMaterial">
            <input asp-for="PackageItemId" type="hidden" />
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        <label asp-for="CatalogItem.ModelNum" class="control-label"></label>
                        <input asp-for="CatalogItem.ModelNum" class="form-control" readonly />
                    </div>
                </div>
                <div class="col">
                    <div class="mb-3">
                        <label asp-for="CatalogItem.CatalogNum" class="control-label"></label>
                        <input asp-for="CatalogItem.CatalogNum" class="form-control" readonly />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        <label asp-for="CatalogItem.Descr" class="control-label"></label>
                        <input asp-for="CatalogItem.Descr" class="form-control" readonly />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        <label asp-for="CatalogItem.CustomerDesc" class="control-label"></label>
                        <input asp-for="CatalogItem.CustomerDesc" class="form-control" readonly />
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <input type="submit" value="Delete" class="btn btn-danger" />
                <a class="btn btn-secondary" asp-action="EditPackageItem" asp-route-id="@Model.PackageItemId">Cancel</a>
            </div>
        </form>
    </div>
</div>

MountainAir.Web/Views/Packages/EditPackage.cshtml
@model MountainAir.Common.Data.Models.Package
@{
    ViewData["Title"] = "Edit " + Model.PackageName;
    NavPages.AddActivePage(ViewData, NavPages.Pages.Packages);
}

<div class="card p-2">
    <div class="card-header d-flex justify-content-between">
        <h5 class="card-title">@ViewData["Title"]</h5>
        <a asp-action="Index" asp-controller="Packages" class="btn btn-sm btn-secondary">Back to Packages</a>
    </div>
    <div class="card-body">
        <form asp-action="EditPackage">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="AddBy" type="hidden" />
            <input asp-for="AddDate" type="hidden" />
            <input id="hidPackageId" asp-for="PackageId" type="hidden" />
            <div class="col w-50">
                <div class="mb-3">
                    <label asp-for="PackageName" class="form-label"></label>
                    <input asp-for="PackageName" class="form-control" />
                    <span asp-validation-for="PackageName" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="ProfitMargin" class="form-label"></label>
                    <input asp-for="ProfitMargin" class="form-control" type="number" />
                    <span asp-validation-for="ProfitMargin" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="AhriRating" class="form-label"></label>
                    <input asp-for="AhriRating" class="form-control" type="number" />
                    <span asp-validation-for="AhriRating" class="text-danger"></span>
                </div>
                <div class="mb-3 form-check">
                    <label asp-for="Active" class="form-check-label"></label>
                    <input asp-for="Active" class="form-check-input" />
                </div>
                <div class="mb-3">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a class="btn btn-secondary" asp-action="Index">Cancel</a>
                </div>
            </div>
        </form>
    </div>
    <hr />
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <h5 class="card-title">Equipment</h5>
            <a class="btn btn-success" asp-action="AddPackageItem" asp-route-id="@Model.PackageId">
                <i class="fa fa-plus-circle"></i> Add Equipment
            </a>
        </div>
        <div class="card-body">
            <table id="tblEquipment" class="table table-condensed table-striped">
                <thead>
                    <tr>
                        <th></th>
                        <th>Section</th>
                        <th>Catalog Number</th>
                        <th>Description</th>
                        <th>Model Number</th>
                        <th>Quantity</th>
                        <th>Labor</th>
                        <th>Price</th>
                        <th>Active</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.PackageItems.OrderBy(i => i.Section))
                    {
                        <tr>
                            <td>
                                <a asp-action="EditPackageItem" asp-route-id="@item.PackageItemId"><i class="fa fa-edit btn-outline-warning"></i></a>
                                <a asp-action="DeletePackageItem" asp-route-id="@item.PackageItemId"><i class="fa fa-trash btn-outline-danger"></i></a>
                            </td>
                            <td>@item.OptionSection</td>
                            <td>@item.CatalogItem.CatalogNum</td>
                            <td>@item.CatalogItem.Descr</td>
                            <td>@item.CatalogItem.ModelNum</td>
                            <td>@item.Quantity</td>
                            <td>@item.Labor</td>
                            <td>@item.Price?.ToString("C")</td>
                            <td>@(item.CatalogItem.Active ? "Yes" : "No")</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
<script type="text/javascript">
    $(document).ready(function () {
        $('#tblEquipment').DataTable();
    });
</script>
}



MountainAir.Web/Views/Packages/EditPackageMaterial.cshtml
@model MountainAir.Common.Data.Models.PackageMaterial
@{
    ViewData["Title"] = "Edit Material";
    NavPages.AddActivePage(ViewData, NavPages.Pages.Packages);
}

<div class="card">
    <div class="card-header d-flex justify-content-between">
        <h5 class="card-title">@ViewData["Title"]</h5>
        <a asp-action="EditPackageItem" asp-controller="Packages" asp-route-id="@Model.PackageItemId" class="btn btn-sm btn-secondary">Back To Equipment</a>
    </div>
    <div class="card-body">
        <form asp-action="EditPackageMaterial">
            <input type="hidden" asp-for="PackageItemId" />
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        <label asp-for="CatalogItem.CatalogNum" class="form-label"></label>
                        <input asp-for="CatalogItem.CatalogNum" class="form-control" readonly />
                    </div>
                </div>
                <div class="col">
                    <div class="mb-3">
                        <label asp-for="CatalogItem.ModelNum" class="form-label"></label>
                        <input asp-for="CatalogItem.ModelNum" class="form-control" readonly />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        <label asp-for="CatalogItem.Descr" class="form-label"></label>
                        <input asp-for="CatalogItem.Descr" class="form-control" readonly />
                    </div>
                </div>
                <div class="col">
                    <div class="mb-3">
                        <label asp-for="CatalogItem.CustomerDesc" class="form-label"></label>
                        <input asp-for="CatalogItem.CustomerDesc" class="form-control" readonly />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        <label asp-for="Quantity" class="form-label"></label>
                        <input asp-for="Quantity" class="form-control" />
                    </div>
                </div>
                <div class="col">
                    <div class="mb-3">
                        <label asp-for="Price" class="form-label"></label>
                        <input asp-for="Price" class="form-control" />
                    </div>
                </div>
                <div class="col">
                    <div class="mb-3">
                        <label asp-for="Labor" class="form-label"></label>
                        <input asp-for="Labor" class="form-control" />
                    </div>
                </div>
            </div>
            <input type="submit" value="Save" class="btn btn-primary" />
        </form>
    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

MountainAir.Web/Views/Packages/PackageItems.cshtml
@model PackageEditingModel
@{
    ViewData["Title"] = $"Package Items for {Model.Package.PackageName}";
    NavPages.AddActivePage(ViewData, NavPages.Pages.Packages);
}

@section Head {

}

<div class="card">
    <div class="card-header d-flex justify-content-between">
        <h5 class="card-title">
            @ViewData["Title"]
        </h5>
        <a asp-action="Index" asp-controller="Packages" class="btn btn-sm btn-secondary">Back to Package List</a>
    </div>
    <div class="card-body">
        <table id="tblPackageItems" class="table table-striped table-condensed table-hover">
            <thead></thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script type="text/javascript">
        const packageId = '@(Model.Package.PackageId)';
        const catalogItems = @(Html.Raw(Model.CatalogItemsJson));
    </script>
    <script src="/js/Packages/PackageItems.js"></script>
}